### ISSUE TITLE
spanner.instance.exists - function's callback did not return bool value

### ISSUE THREAD

**Issue by Chipintoza** [googleapis/nodejs-spanner#23] opened 2017-10-30 11:25 UTC
OS: Mac OSX 10.13
Node.js version: 6.9.3
npm version: 5.5.1
version: 0.8.0

spanner.instance('name').exists((err, exists) =>
in this callback exists = undefined when instance exist

**Comment by stephenplusplus** [comment] 2017-10-30 13:32
Hey @Chipintoza, I think this is a bug that affects all of our libraries. I'm going to close this in favor of https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2702, which reported it a few days ago.

**Closed by stephenplusplus** 2017-10-30 13:32 UTC

**Comment by Chipintoza** [comment] 2017-10-30 18:37
hi @stephenplusplus, just for information: it works if i change only spanner version 0.7.1

**Comment by Chipintoza** [comment] 2017-11-23 17:01
@stephenplusplus @lukesneeringer  I update spanner to 0.8.1 but it still not works...

**Comment by callmehiphop** [comment] 2017-11-24 15:01
@Chipintoza I'm testing this locally and it seems to be working fine, is there any chance there could put together a repo together that reproduces the issue in as few lines as possible?

**Comment by Chipintoza** [comment] 2017-11-27 20:13
@callmehiphop thank you... 
i make my situation in test project for you [spanner-tests](https://github.com/Chipintoza/spanner-tests)

There is old - package-lock.json
run: 
**npm install**
and then run:
**node schema.js**
log is:

> chipintozamac:spanner-tests Chipintoza$ npm install

> > grpc@1.6.6 install /Users/Chipintoza/GSS Projects/Tests/1234/spanner-tests/node_modules/@google-cloud/common-grpc/node_modules/grpc
> > node-pre-gyp install --fallback-to-build --library=static_library
> 
> [grpc] Success: "/Users/Chipintoza/GSS Projects/Tests/1234/spanner-tests/node_modules/@google-cloud/common-grpc/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64/grpc_node.node" is installed via remote
> 
> > grpc@1.3.8 install /Users/Chipintoza/GSS Projects/Tests/1234/spanner-tests/node_modules/grpc
> > node-pre-gyp install --fallback-to-build --library=static_library
> 
> [grpc] Success: "/Users/Chipintoza/GSS Projects/Tests/1234/spanner-tests/node_modules/grpc/src/node/extension_binary/grpc_node.node" is installed via remote
> 
> > protobufjs@6.8.1 postinstall /Users/Chipintoza/GSS Projects/Tests/1234/spanner-tests/node_modules/@google-cloud/spanner/node_modules/protobufjs
> > node scripts/postinstall
> 
> added 477 packages in 13.634s
> chipintozamac:spanner-tests Chipintoza$ node schema.js 
> { Error: Instance already exists: projects/spanner-gss-ge/instances/gss-data
>     at /Users/Chipintoza/GSS Projects/Tests/1234/spanner-tests/node_modules/grpc/src/node/src/client.js:442:17
>   code: 6,
>   metadata: 
>    Metadata {
>      _internal_repr: 
>       { 'google.rpc.resourceinfo-bin': [Array],
>         'grpc-status-details-bin': [Array] } } }

when i delete old  package-lock.json
everything work fine:
it looks dependency problems. and in the first situation the wrong grpc@1.3.8 version is installed

**Comment by Chipintoza** [comment] 2017-11-27 20:18
@callmehiphop - you need to change spanner.json

**Comment by callmehiphop** [comment] 2017-11-27 20:41
@Chipintoza I don't need a copy of spanner.json, I would delete that ASAP and squash your commits to remove it from history.

**Comment by callmehiphop** [comment] 2017-11-28 14:31
As you pointed out @Chipintoza the issue here is with our dependencies. The good news is there is already a plan in motion to phase out one of these dependencies (`common-grpc`). The bad news is that it is a pretty significant change so it will take some time.

**Comment by Chipintoza** [comment] 2017-11-28 16:18
@callmehiphop than you. i will always remove package-lock.json :)
