### ISSUE TITLE
src/transction:fix Snapshot.createReadStream on error this.begin() invocation when no transactionID is detected and it was not aborted

### ISSUE THREAD

**Issue by odeke-em** [googleapis/nodejs-spanner#2170] opened 2024-10-22 06:48 UTC
As a consequence of this problem, in my observability changes I have to invoke `await this.begin()`  so as to ensure proper span production but @surbhigarg raised a point in a code review with

> Can we hold on this change of making 'error' event async. I know this would mean that our few spans wont work correctly.  
I am working on another PR to see if this check can be removed https://github.com/googleapis/nodejs-spanner/pull/2168 
>
>Adding async here will cause other issues like in below when `runTransactionAsync` method tries to insert an invalid error, normally this `error` event is invoked first and then `catch` block. But if you add `async` here, this would make `catch` block invoked first as `error` event is called asynchronously which will cause other issues. 
```
try {
    await database.runTransactionAsync(async transaction => {
      await transaction.run(
        "INSERT INTO Singers (SingerId, FirstName) VALUES (310, 'abc')"
      );
      await transaction.commit();
    });
    await database.runTransactionAsync(async transaction => {
      await transaction.run(
        "INSERT INTO Singers (SingerId, FirstName) VALUES (310, 'abc')"
      );
      await transaction.commit();
    });
  } catch (err) {
    console.error('ERROR:', err);
    // throw err;
  } finally {
    database.close();
  }
  ```
  
  Remove this change and add a bug where we mention what scenarios are not working and I will take it up separately.

_Originally posted by @surbhigarg92 in https://github.com/googleapis/nodejs-spanner/pull/2158#discussion_r1809085825_

**Comment by surbhigarg92** [comment] 2024-11-11 06:59
@odeke-em IMU this issue is duplicate of other issue raised https://github.com/googleapis/nodejs-spanner/issues/2159 

`this.begin` is invoked for non-aborted errors in [createReadStream](https://github.com/googleapis/nodejs-spanner/blob/main/src/transaction.ts#L766) and [runStream](https://github.com/googleapis/nodejs-spanner/blob/main/src/transaction.ts#L1358) 

Closing this bug . Pleas feel free to re-open if you feel otherwise.

**Closed by surbhigarg92** 2024-11-11 06:59 UTC
Labels: api: spanner
