### ISSUE TITLE
Auto transaction ping “SELECT 1” to prevent getting aborted due to 10s idle transactions

### ISSUE THREAD

**Issue by KennyCCK** [googleapis/nodejs-spanner#1349] opened 2021-04-21 08:18 UTC
**Is your feature request related to a problem? Please describe.**
- I have a use-case with long R/W transactions from a Cloud Spanner user @josecaodaglio who is also having serious difficulties to both debug and processing the transactions due to the 10s abort. The long R/W transactions are unavoidable due to business logic, it involves calls to external API services between statements and the nature of the business flow does not allow idempotency.

 **Describe the solution you'd like**
As this topic is mentioned often and as highlighted by @skuruppu separately in Spring Cloud GCP library [1] with the Feature Request is now created for java-spanner [2], is it possible for the feature to be considered for NodeJS Spanner client as well?

The feat [2] was mentioned as:
```
Read/write transactions in Cloud Spanner are automatically aborted by Cloud Spanner if they are idle for more than 10 seconds. For connection based APIs this can pose a challenge, especially during debugging, as stepping through the code will in most cases cause the active read/write transaction to be aborted because of the long delays between each step.
```
which is exactly the case.

It would be great if the NodeJS Spanner client supports it natively, maybe allow to set as an option when initializing the client or the R/W transaction?

 **Describe alternatives you've considered**
As a workaround, there is currently an ad-hoc solution implemented using setInterval() that performs “background” pings for the concurrent transactions. Although this is working to an extent, however it requires much manual effort and it is not perfect as it is bound to the single threaded nature of NodeJS (the main event loop). 

Under heavy concurrency and in a restricted resources environment on the cloud such as GCE VM, etc. the main thread tends to get blocked causing the ping not firing in time.

 **Additional context**
Understandably, NodeJS’s Javascript is not the same as Java where it offers real multithreading, perhaps the feature can be achieved through the recent promising WebAssembly (wasm) or the C++ addon for NodeJS [3]?

[1] https://github.com/spring-cloud/spring-cloud-gcp/issues/2453#issuecomment-655845793 
[2] https://github.com/googleapis/java-spanner/issues/346
[3] https://stackoverflow.com/questions/11051070/node-js-c-addon-threading

**Comment by skuruppu** [comment] 2021-04-21 22:50
Thanks a lot for submitting this issue @KennyCCK and @josecaodaglio.

We've had several discussions about this in the various languages that we have client library implementations. The consensus we've come to is that this type of ping to keep transactions alive makes sense for a connections based API (like the Java connection API implementation referred to in [2]) and maybe even for DBAPI (which is the connection layer used for Python ORMs). But the Cloud Spanner client libraries are not connection-based APIs. So we are hesitant to implement this support in client libraries directly because it may mean that users accidentally keep transactions alive when they don't mean to which can be very expensive.

@olavloite do you have any thoughts on this?

**Comment by olavloite** [comment] 2021-04-22 06:27
I agree that this is something that should probably not be added to the transaction runners in the different client libraries. The 10 second time limit is a safety measure to prevent transactions to hold on to locks for longer than necessary, and introducing an option that would make it easy for applications to 'turn off' this safety measure could trigger applications to use this instead of looking into ways to decrease the idle time in the transaction.

Put another way: If this was something that is not really an issue, the backend could also include an option in the `BeginTransaction` RPC that would allow the client to set a higher idle-timeout. That is however not the case, and the client library is intended to allow easy but also idiomatic access to Cloud Spanner. In my opinion, offering an option to turn off or increase this timeout using a simple option that could be turned on/off would be compliant with offering ease-of-use, but it would be against the intention of offering idiomatic access to Cloud Spanner.

Often these idle times are caused by external processes that are executed as part of the transaction. One issue that you need to take into account in such a use case is that Cloud Spanner could abort __any__ read/write transaction, and not only if the transaction is idle for more than 10 seconds, and that the external process could be called a second or even more times if the transaction is retried. If it is a process that always takes a long time, it might be worth considering redesigning the application at that point to place the external process outside of the transaction (or probably: Use a transaction before and after the process to indicate that the process has been started and completed).

**Comment by josecaodaglio** [comment] 2021-04-22 14:35
Hello guys, thanks very much for your input, let me put the outside developer perspective, I understand that you have several motivations to require such ping but here is my points


1.  These ping makes debug (so develop) almost impossible. When I am debugging, I can't think. A problem that should take 20 minutes to find If I had time to compare, look into the stack, look previous variables in the stack, becomes a nightmare and it will last days.  It is just insane.
2. These ping generates a lot of problems to execution as well (not only debugging) 
a-  Say that I insert, get a value from a table and for some reason I have to make a calculation, backtracking and so on, one call to nodejs event loop only, no async.. I will be dead after 10s. You may say "Ok just add a sleep(1)" but this is the kind of theoretical answer that does not take into consideration the complexity of the developed systems. The code may be split into thousands of lines and third part libraries so there is no way to add dozens of splits or be sure that this will somehow work,
b- Even if there is an async call I can't guarantee nothing. I just had an issue with this. I was parallelising a call to datastore and it simply wouldn't call my `select 1`, the event loop was overwhelming being used by the datastore calls even if my setTimeout was defined by the transaction controller way before the calls to datastore. 

I think that this is so serious and damaging that Spanner should be considered partially compatible with nodejs.  There is no way to debug or handle complex interactions using spanner and nodejs.  If your use case is just inserting a thousand of lines and commit it, fine, but I don't see how it can work for real word complex interactions.

As you know, spanner is the only database AFAIK that demands this from developers. Even milliseconds response database like redis has no issue with this. Had some similar problems with Rabbit but eventually I found a way out.

In my very limited perspective, this PING should be handled by spanner client in the C/C++ part in the library, so it would not under the nodejs event loop. Or the server wake up each X seconds and kills sessions that didn't ping (like most of databases do)

Thanks

**Comment by olavloite** [comment] 2021-04-22 15:18
@josecaodaglio Thanks for the input, that is very valuable.

> 1. These ping makes debug (so develop) almost impossible. When I am debugging, I can't think. A problem that should take 20 minutes to find If I had time to compare, look into the stack, look previous variables in the stack, becomes a nightmare and it will last days.  It is just insane.

That is a good point. When debugging transaction code you will hit the 10 second idle time very quickly, and that can make stepping through the code a lot more difficult. So for debugging purposes I can certainly see a case for a built-in solution that would make it easier.

> Or the server wake up each X seconds and kills sessions that didn't ping (like most of databases do)

Well, that is exactly what it does. Only the 'kill time' for transactions (10 seconds) is a lot lower than most databases have, and that is to ensure that (serializable) read/write transactions do not hold on to locks for longer than necessary. Sessions are also automatically garbage collected by the backend if they are not used for more than 1 hour.

My feeling regarding this is that the client library should at least be very careful before it starts 'working around' a limit that the backend has intentionally set, and that is not configurable (on the backend).

**Comment by josecaodaglio** [comment] 2021-04-22 18:25
> Only the 'kill time' for transactions (10 seconds) is a lot lower than most databases have, and that is to ensure that (serializable) read/write transactions do not hold on to locks for longer than necessary. Sessions are also automatically garbage collected by the backend if they are not used for more than 1 hour.

Indeed. But maybe this is generating a far worse problem than the one you want to solve.  Just to mention it again, this impacts productions routine as well. 

Probably the best person to judge the trade off would be the system administrator. In my case, the probability of dropping connection is almost zero. On the other hand, I have several transactions that last more than 10s running without being able to send a ping.

**Comment by skuruppu** [comment] 2021-04-23 04:17
@josecaodaglio thanks for the details of the use cases where you will find this feature useful. This helps a lot.

I agree that for (1) and (2a) it would help to have this feature. We'll talk with the team and see if there's a way to satisfy this.

For (2b), I don't think the client library automatically doing the pings would help either. If you're not able to make the `select 1` calls on your side of the application, I would imagine the client library code would also have trouble making the calls.

**Comment by josecaodaglio** [comment] 2021-04-23 04:32
Hello Skuruppu

For 2b maybe there is a solution on your side. Usually one library has a low level part writen in C/C++ and another part in JS (in the nosejs case). The JS would access the low level part that has its functiinalities wrapped by the JS part. So the ping could bê in the low level code wich is not ececuted by the nodejs event loop. I use several JS libraries that actually open another threads and they all use the low level C part of the library.

**Comment by KennyCCK** [comment] 2021-04-28 09:57
Thanks for considering this, 
looking forward to hear more about potential ways to overcome the matters highlighted.

I'm not sure about the direction of the client library whether there would be plans to touch lower levels such as C/C++, but given some possible options such as C++ addons or wasm, there could be a chance to realize it.
(or perhaps if it is possible to provide some easy ways / steps that users can integrate)

Just a small share, there is an unofficial [spanner-cli](https://github.com/cloudspannerecosystem/spanner-cli) interactive command line tool (developed with Go) that I found very useful to test transaction behaviors in Spanner at the very basic level. The tool has a built-in `SELECT 1` every 5 seconds when transactions are opened. (I could see the calls from the stackdriver logs)

Although it would be great if client libraries allows debugging natively, the tool works as a minimum outside-app-context debugging workaround for now. (but rather tedious to be used to test complex transactions)

**Comment by skuruppu** [comment] 2021-04-29 03:38
Thanks for your patience @josecaodaglio and @KennyCCK. I don't yet have answers on whether the team agrees to implementing support for (1) and (2a).

For (2b), the Spanner client library has no C/C++ layers, not even at the gRPC layer of the library. So there's no way to get access to an extra thread unless you specifically import some addon that would allow you to add this yourself. We won't do this generically within the client library.

If your application is trying to do a lot within the primary process, would it be an option to move the spanner work to a sub process? Maybe then the spanner application will have sufficient resources to do the "select 1" queries.

It's hard for me to make any concrete recommendation without knowing some details about your use case. Let us know here or through the support channel on any details so that we can help.

**Comment by josecaodaglio** [comment] 2021-04-29 15:41
Hello @skuruppu 

> would it be an option to move the spanner work to a sub process? Or event to shard the spanner calls across multiple node processes? Maybe then the spanner application will have sufficient resources to do the necessary "select 1" queries.

I don't see how can I send a connection object through different worker threads, I can serialize a message, not send objects AFAIK. 

> If your application is trying to do a lot within the primary process

It is not trying to do a lot, it is really standard computation. I am afraid that this is a design issue that Google should look with care.

**Comment by skuruppu** [comment] 2021-05-04 01:03
We had a lengthy discussion about this as a team and still came to the conclusion that we won't support this as a feature in any of the client libraries. Even if it's something users have to opt into, we're still very much concerned that if it's enabled on an application, not all devs working on the app may realize this is the case and end up holding onto transactions unintentionally and cause significant performance problems.

I know this is not the news you wanted to hear. We may reconsider this decision in the future but for now I'll close the issue.

**Closed by skuruppu** 2021-05-04 01:03 UTC
Labels: api: spanner, priority: p3, type: feature request

**Comment by josecaodaglio** [comment] 2021-05-04 10:33
Hello @skuruppu , just to confirm, you are not intend to support any of the cases, even the one that give the admins the choice to set the timeout?
