### ISSUE TITLE
Upgrading retry-request to 4.2.2 makes some requests take a lot longer

### ISSUE THREAD

**Issue by flovouin** [googleapis/nodejs-spanner#1444] opened 2021-08-01 09:13 UTC
I involuntarily upgraded to `retry-request@4.2.2` (through `@google-cloud/common@3.7.0` and others) and noticed that some of my tests were resulting in timeouts. It turns out that some operations take a lot longer (but don't hang, it's just that my test had a maximum running time of 5 seconds).

For example, trying to read from an index that doesn't exist using a snapshot will take several seconds before failing, which isn't the case with `retry-request@4.2.0`.

```js
await snapshot.read(table.name, { index: "nope" });
```

#### Environment details

  - OS: (At least) macOS
  - Node.js version: `v14.17.0`
  - npm version: `7.19.1`
  - `@google-cloud/spanner` version: `5.12.0`

#### Steps to reproduce

  1. Clone https://github.com/flovouin/spanner-retry-request-issue
  2. Install dependencies
  3. Ensure Docker is running (so that the Spanner emulator can be started)
  4. Run `./run-test.sh 4.2.0 && ./run-test.sh 4.2.2`

You should get something like this:

```
Using retry-request 4.2.0
5 NOT_FOUND: No index 'nope' was found for table 'test'.
Took 21 ms
Using retry-request 4.2.2
5 NOT_FOUND: No index 'nope' was found for table 'test'.
Took 6745 ms
```

Let me know if you need additional details. 🙂

Cheers,

**Comment by skuruppu** [comment] 2021-08-04 01:14
Thanks for the report @flovouin.

Since @stephenplusplus maintains `retry-request`, I am assigning this to him. If you can please take a look, and see if the issue is specific to Spanner or if it's a generall issue, that would be great.

**Comment by stephenplusplus** [comment] 2021-08-04 20:53
Thanks for the report and the reproduction case, @flovouin!

Ironically, this delay we see in the test script is due to a bug fix. `retry-request@4.2.2` corrected a bug where we were not overriding a user's settings to replace any undefined values with the default values. Due to the bug, in versions < 4.2.2, `retry-request` was basically being told not to retry the call made from this library, in this case `snapshot.read()`.

Since `retry-request` corrected the bug, the call to `snapshot.read()` in the test script which expects an error is first being retried per the default retry configuration settings. That is what is introducing the delay.

@skuruppu this is the error: `5 NOT_FOUND: No index 'nope' was found for table 'test'.`. Is this error expected to be retried? We might be stuck when parsing gRPC errors due to this issue: https://github.com/stephenplusplus/retry-request/blob/f06f6351bd1f4d635804fb1c77e14984f2c9b2e4/index.js#L146.

**Comment by skuruppu** [comment] 2021-08-05 03:43
Thanks @stephenplusplus for taking a look.

`NOT_FOUND` should not be a retriable error from the perspective of the [Spanner retry config](https://github.com/googleapis/googleapis/blob/882e6d69a30e4bde445dd33c710f1235b81270c7/google/spanner/v1/spanner_grpc_service_config.json#L11) for a `StreamingRead` which is what `snapshot.read()` ends up calling.

I know we've had some issues with the Spanner retry config not being respected by Node.js. E.g. https://github.com/googleapis/gax-nodejs/issues/902 and https://github.com/googleapis/gax-nodejs/issues/1013 so I wonder if these are all related.

**Comment by flovouin** [comment] 2021-08-31 05:44
Not super urgent, but would you have an update on this one? 🙂

**Comment by skuruppu** [comment] 2021-09-08 01:50
@stephenplusplus any ideas on why `NOT_FOUND` errors are being retried here?

**Comment by flovouin** [comment] 2022-02-24 09:13
Hi @skuruppu and @stephenplusplus, we're still impacted by this. Has there been any follow up?

**Comment by ansh0l** [comment] 2022-02-24 09:16
Assigning to @asthamohta

**Comment by ansh0l** [comment] 2022-02-24 09:19
@flovouin : This seems to have fallen through the cracks. Apologies for that. @asthamohta will take a look.

**Comment by stephenplusplus** [comment] 2022-03-02 20:59
Hi all, I'm not working on this project anymore. I'm happy to transfer the `retry-request` library to the google org, or add anybody as an owner to the existing repo. For now, I've added @ansh0l.

**Comment by surbhigarg92** [comment] 2022-09-13 05:24
Hi @flovouin Have you tried upgrading to the latest version of `retry-request` ? 
If not , please try to upgrade to latest version and let us know if you are still facing the issue.

**Comment by flovouin** [comment] 2022-09-13 12:12
The issue still occurs.

**Comment by surbhigarg92** [comment] 2022-09-21 11:07
@flovouin We have observed a weird behaviour while trying to analyse this issue. 
When trying to run the same code against emulator we are getting the same error as mentioned by you. 
However when we try to run the same code against GCP we are not seeing this behaviour.

Can you please try running the same code against GCP and check ?

Note: You might have to make a minor change in the sample code in order to run against GCP
```
await snapshot.read(table.name, {
      columns: ['Id'],
      index: "nope",
    });

```

**Comment by flovouin** [comment] 2022-10-12 07:36
@surbhigarg92 Indeed, when running against a GCP instance the code is not as slow (it still takes 1 second, but I expect this to be due to establishing the connection rather than retries). Here are the errors I get from GCP and the emulator:

**GCP**
```
Error: 5 NOT_FOUND: Index not found on table test: nope
    at Object.callErrorFromStatus (/test/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/test/node_modules/@grpc/grpc-js/build/src/client.js:360:49)
    at /test/node_modules/@grpc/grpc-js/build/src/call-stream.js:111:35
    at Object.onReceiveStatus (/test/node_modules/grpc-gcp/build/src/index.js:73:29)
    at InterceptingListenerImpl.onReceiveStatus (/test/node_modules/@grpc/grpc-js/build/src/call-stream.js:106:23)
    at Object.onReceiveStatus (/test/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /test/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/test/node_modules/@grpc/grpc-js/build/src/client.js:343:34)
    at ServiceClientImpl.<anonymous> (/test/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /test/node_modules/@google-cloud/spanner/build/src/v1/spanner_client.js:221:29
    at /test/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:38:28
    at /test/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at Object.request (/test/node_modules/google-gax/build/src/streamingCalls/streaming.js:130:40)
    at makeRequest (/test/node_modules/retry-request/index.js:141:28)
    at retryRequest (/test/node_modules/retry-request/index.js:109:5)
    at StreamProxy.setStream (/test/node_modules/google-gax/build/src/streamingCalls/streaming.js:121:37)
    at StreamingApiCaller.call (/test/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:54:16) {
  code: 5,
  details: 'Index not found on table test: nope',
  metadata: Metadata {
    internalRepr: Map(3) {
      'grpc-server-stats-bin' => [ [Buffer [Uint8Array]] ],
      'google.rpc.resourceinfo-bin' => [ [Buffer [Uint8Array]] ],
      'grpc-status-details-bin' => [ [Buffer [Uint8Array]] ]
    },
    options: {}
  },
  statusDetails: [
    ResourceInfo {
      resourceType: 'spanner.googleapis.com/Index',
      resourceName: 'nope',
      description: 'Index not found on table test'
    }
  ]
}
```

**Emulator**
```
Error: 5 NOT_FOUND: No index 'nope' was found for table 'test'.
    at Object.callErrorFromStatus (/test/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/test/node_modules/@grpc/grpc-js/build/src/client.js:360:49)
    at /test/node_modules/@grpc/grpc-js/build/src/call-stream.js:111:35
    at Object.onReceiveStatus (/test/node_modules/grpc-gcp/build/src/index.js:73:29)
    at InterceptingListenerImpl.onReceiveStatus (/test/node_modules/@grpc/grpc-js/build/src/call-stream.js:106:23)
    at Object.onReceiveStatus (/test/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /test/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/test/node_modules/@grpc/grpc-js/build/src/client.js:343:34)
    at ServiceClientImpl.<anonymous> (/test/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /test/node_modules/@google-cloud/spanner/build/src/v1/spanner_client.js:221:29
    at /test/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:38:28
    at /test/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at Object.request (/test/node_modules/google-gax/build/src/streamingCalls/streaming.js:130:40)
    at Timeout.makeRequest [as _onTimeout] (/test/node_modules/retry-request/index.js:141:28)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7) {
  code: 5,
  details: "No index 'nope' was found for table 'test'.",
  metadata: Metadata {
    internalRepr: Map(2) {
      'content-type' => [ 'application/grpc' ],
      'grpc-status-details-bin' => [ [Buffer [Uint8Array]] ]
    },
    options: {}
  }
}
```

**Comment by surbhigarg92** [comment] 2022-10-13 10:12
@flovouin Since there is no issue with either NodeJs library or with retry-request library while running the project against GCP, We are closing this bug. Emulator team is already tracking the issue with emulator internally. 

Please feel free to open the bug if this does not address your concerns.

**Closed by surbhigarg92** 2022-10-13 10:12 UTC
Labels: type: bug, priority: p2, :rotating_light:, api: spanner
