### ISSUE TITLE
Errors in Google Cloud Functions' Emulator

### ISSUE THREAD

**Issue by merlinnot** [googleapis/nodejs-spanner#83] opened 2018-01-05 12:52 UTC
I'm getting

> Error: Cloud Spanner API has not been used in project firebase-cli before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/spanner.googleapis.com/overview?project=firebase-cli then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

It seems like the project name is not derived correctly.

#### Environment details

  - OS: Linux merlinnot 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
  - Node.js version: v6.11.5
  - npm version: v3.10.10
  - @google-cloud/spanner version: ^0.10.0

#### Steps to reproduce

  1. Write any, even the simplest cloud function
  2. Start Firebase emulator/shell
  3. Run the function

**Comment by stephenplusplus** [comment] 2018-01-09 18:26
If you provide the project ID to the Spanner instantiation, does it work correctly?

**Comment by merlinnot** [comment] 2018-01-12 08:08
I've tried both
```ts
const spanner = new Spanner({projectId: 'my-project-id'})
```
and
```ts
const spanner = new Spanner()
```

Neither worked for me.

**Comment by stephenplusplus** [comment] 2018-01-12 19:34
I wonder if this relates to https://github.com/googleapis/nodejs-pubsub/issues/38

To test, you could try instantiating spanner differently:

```diff
- const spanner = new Spanner()
+ const spanner = Spanner()
```

**Comment by merlinnot** [comment] 2018-01-17 16:45
Unfortunately, it doesn't help.

**Comment by haseebr** [comment] 2018-01-19 13:43
I'm having the same error but with cloud KMS. 

`{ Error: Google Cloud Key Management Service (KMS) API has not been used in project firebase-cli before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudkms.googleapis.com/overview?project=firebase-cli then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
`

My node version is v6.9.1 and npm v3.10.8.

**Comment by armenr** [comment] 2018-02-03 04:36
^^ Same problem as @haseebr

**Comment by stephenplusplus** [comment] 2018-02-05 18:56
I'm having trouble getting an environment configured to attempt to reproduce. @merlinnot sorry, but would you mind trying this again in 1.0.3?:

```js
const spanner = new Spanner({projectId: 'my-project-id'})
```

We should be localizing that `projectId` value, and not asking the environment for its own (which is where `firebase-cli` would come in.

**Comment by merlinnot** [comment] 2018-02-09 17:00
The error is still the same.

You can just take any [sample](https://github.com/firebase/functions-samples) function and try to do literally anything with Spanner using [shell](https://firebase.google.com/docs/functions/local-emulator#install_and_configure_the_cloud_functions_shell) to reproduce :)

I guess something takes priority here, but it's not an env variable... I've literally checked all env variables and `firebase-cli` doesn't even exist.

Correct values (my project ids) live in `GCLOUD_PROJECT` and `GCP_PROJECT`.

You can initialize all other SDKs I know without specifying project id, it's taken from the env variable by default. It works fine.

**Comment by pmadruga** [comment] 2018-03-30 20:10
I landed here after a google search for another library but with the exact same issue. The solution was to include the `keyFilename` property.

```
const client = new text-to-speech.TextToSpeechClient({
    projectId: 'your-project-id',
    keyFilename: '/path/to/keyfile.json',
  });
```

Hope it helps.

**Comment by callmehiphop** [comment] 2018-04-02 14:09
@stephenplusplus I'm afraid I don't have the bandwidth to take this on at the moment, so I'll have to send it back your way.

**Comment by stephenplusplus** [comment] 2018-04-02 15:48
I'm going to leave it unassigned for now, as chances are you'll have the time to check it out before me (this is about impossible to attempt on Windows).

**Comment by JustinBeckwith** [comment] 2018-10-03 04:33
Greetings folks!  It looks like @pmadruga has a reasonable work around here.  If this is still an issue... please do let us know!

**Closed by JustinBeckwith** 2018-10-03 04:33 UTC
Labels: :rotating_light:, priority: p2, type: bug
