### ISSUE TITLE
Insert over max mutations per commit hangs

### ISSUE THREAD

**Issue by walshie4** [googleapis/nodejs-spanner#116] opened 2018-02-08 02:19 UTC
#### Environment details

  - OS: Google Container optimized OS
  - Node.js version: v8.9.4
  - npm version: v5.6.0
  - @google-cloud/spanner version: v1.0.3

#### Steps to reproduce

  1. Setup brand new spanner instance
  2. Add table schema
  3. Do large insert which is over 20,000 mutations
  4. Call does not return (resolved or rejected promise or anything else for that matter) or throw an error

I understand I'm doing something explicitly against Spanner's limits however I feel having this hang is poor response.  It seems odd to have users have to do mutation checks themselves rather than have Spanner return an error when doing something over the limits.

**Comment by stephenplusplus** [comment] 2018-02-09 21:39
How did you determine the problem was that it was over a maximum amount of mutations? Is it written somewhere that there is a limit?

**Comment by vkedia** [comment] 2018-02-09 22:35
Yes it is documented here:
https://cloud.google.com/spanner/quotas

In this case the server would return an error.

**Comment by stephenplusplus** [comment] 2018-02-11 21:13
Thanks. When I tried to reproduce, I received the expected error:

```
Error: The transaction contains too many mutations. Insert and update operations count with the multiplicity of the number of columns they affect. For example, inserting values into one key column and four non-key columns count as five mutations total for the insert. Delete and delete range operations count as one mutation regardless of the number of columns affected. The total mutation count includes any changes to indexes that the transaction generates. Please reduce the number of writes, or use fewer indexes. (Maximum number: 20000)
```

Could you show the code you're using?

**Comment by stephenplusplus** [comment] 2018-02-20 20:40
Being unable to reproduce, I'm going to close the issue. If you can provide reproduction code, I'll happily try again.

**Closed by stephenplusplus** 2018-02-20 20:40 UTC
Labels: priority: p2, type: question
