### ISSUE TITLE
Error 14 UNAVILABLE: EOF

### ISSUE THREAD

**Issue by walshie4** [googleapis/nodejs-spanner#183] opened 2018-04-30 19:19 UTC
#### Environment details

  - OS: CoreOS
  - Node.js version: v8.9.6
  - npm version: v5.6.0
  - `@google-cloud/spanner` version: v1.4.1

#### Steps to reproduce

  Will attempt to create some if needed.

Hello 👋 

I have a set of APIs using this spanner library and as a transfer over a substantial amount of load (a few thousand requests per second) to these APIs I start to get errors from spanner with the following message: `14 UNAVAILABLE: EOF`.

Looking around it seems I should simply have to retry this request to have a good chance at succeeding.  Curious why this is not a case the library handles for me (I believe I saw some mentions of auto-reties for other transient errors somewhere in the docs).  Additionally I would like to better understand what is going on here so I can solve the real underlying issue.

Is this spanner trying to tell me that I need to scale up my cluster in order to provide more reliable throughput?  Or is this simply something I should expect to run into from time to time?

**Comment by walshie4** [comment] 2018-05-01 02:45
Was just looking through the logs, not sure if this is always happening but right before that I get a couple `timeout acquiring session` errors.  My `acquireSession` timeout is `4000ms`, with a min pool of 100 & max of 500.

Generally curious about how y'all suggest we setup an automatically scaled system with this spanner library's pooling logic in the middle.  I've run into a bunch of issues with getting these things to scale well together.  If you have some quick thoughts that'd be wonderful otherwise I'll open an issue when I get some more time to dig deeper.

**Comment by callmehiphop** [comment] 2018-05-01 20:11
@vkedia you could probably speak to the `EOF` error better than I can, any insights here?

**Comment by vkedia** [comment] 2018-05-02 18:10
This looks like a bug in the client library to me. All kind of UNAVAILABLE errors should be transparently retried by the client library and should never be propagated to the user.

**Comment by vkedia** [comment] 2018-05-02 20:11
@walshie4 couple of observations
- Setting max sessions to 1000 does not mean that the library will necessarily create 1000 sessions. It will only do so if at any point in time you had 1000 concurrent transactions.
- The client library should automatically downsize the session pool and free up any unused sessions. If you set the max to 1000, even if the library ended up creating 1000 sessions to handle burst of traffic, if your steady state traffic is lower it should free up the sessions quickly. Please let us know if you do not observe that happening.
- Essential underlying limit is that your instance have at most 50000 concurrent transactions (assuming 5 nodes) at any point in time. I think it is fine for `num_replicas * max_pool_size > 50000` if you assume that overall traffic across all your replicas would be less than 50000 concurrent requests.

**Comment by callmehiphop** [comment] 2018-05-03 20:09
Sure thing! @walshie4 would you be able to provide us with a minimal amount of code that can reproduce the issue you're seeing?

**Comment by vkedia** [comment] 2018-05-03 20:36
@walshie4 are there some more logs or stack trace that you can share which will help us figure out exactly which call is throwing this error.

**Comment by walshie4** [comment] 2018-05-03 21:06
Sure here are two different stack traces for errors around this message:

![image](https://user-images.githubusercontent.com/945703/39602785-13655000-4edb-11e8-9918-a7a72e1a2527.png)

![image](https://user-images.githubusercontent.com/945703/39602801-1db927fc-4edb-11e8-874e-e63811c3518a.png)

**Comment by walshie4** [comment] 2018-05-03 21:44
A co-worker of mine also saw these rejections after recieving the `UNAVAILABLE: TCP Read failed` error

![image](https://user-images.githubusercontent.com/945703/39604335-88953c46-4ee0-11e8-9a9a-35ba1edaf144.png)

**Comment by vkedia** [comment] 2018-05-03 22:45
@walshie4 Thanks. What spanner method were you calling which returned these errors? From the stack trace I cannot figure that out.

**Comment by walshie4** [comment] 2018-05-03 23:00
Have one more stacktrace I just saw with a new message:

![image](https://user-images.githubusercontent.com/945703/39606352-daf0970c-4ee9-11e8-8d92-2e9a4074f67f.png)


As for the function being called, it's hard to tell exactly which is causing this error but I believe it is from a `spannerDb.run` call.

**Comment by walshie4** [comment] 2018-05-03 23:16
Looking deeper I see the auth and TCP Read messages on both`db.run` and `db.update` calls.  It appears to be more common with `db.run`

**Comment by vkedia** [comment] 2018-05-04 20:04
@callmehiphop can you try to poke into the code and see if there are some places where we do not retry unavailable? Ideally GAPIC should be retrying these, right except for streaming rpcs.

**Comment by callmehiphop** [comment] 2018-05-05 00:08
@vkedia According to the [GAPIC config](https://github.com/googleapis/nodejs-spanner/blob/master/src/v1/spanner_client_config.json#L7) we retry for UNAVAILABLE errors for all non-streaming rpcs.

**Comment by callmehiphop** [comment] 2018-05-06 23:31
@vkedia AFAIK gax does not have any retry logic for streaming rpcs.

**Comment by vkedia** [comment] 2018-05-07 16:06
Yes but does the node.js library not retry broken streams. It should
restart the stream using resume token.

**Comment by callmehiphop** [comment] 2018-05-08 21:35
> Yes but does the node.js library not retry broken streams. It should restart the stream using resume token.

I think it does, but @stephenplusplus should be able to give us a definitive answer.

**Comment by stephenplusplus** [comment] 2018-05-09 18:16
Within our PartialResultStream class, we retry after any error from the last resume token. If we don't have a token, we pass the error along to the user and abort the request.

Here's the code: https://github.com/googleapis/nodejs-spanner/blob/master/src/partial-result-stream.js#L127-L136

```js
return requestsStream
  .intercept('error', function(err) {
    if (lastResumeToken) {
      // We're going to retry from where we left off.
      // Empty queued rows on the checkpoint stream (will not emit them to
      // user).
      batchAndSplitOnTokenStream.reset();
      makeRequest();
      return;
    }

    setImmediate(function() {
      // We won't retry the request, so this will flush any rows the
      // checkpoint stream has queued. After that, we will destroy the user's
      // stream with the same error.
      batchAndSplitOnTokenStream.destroy(err);
    });
  })
  .pipe(batchAndSplitOnTokenStream)
  .on('error', function(err) {
    // If we get this error, the checkpoint stream has flushed any rows it had
    // queued. We can now destroy the user's stream, as our retry attempts are
    // over.
    userStream.destroy(err);
  })
  .on('checkpoint', function(row) {
    lastResumeToken = row.resumeToken;
  })
  .pipe(userStream);
```

**Comment by danoscarmike** [comment] 2018-05-22 21:03
@stephenplusplus anything further on this? 

@walshie4 were you able to provide some code for repro?

**Comment by walshie4** [comment] 2018-05-23 01:40
I have not been able to set anything up yet.  I'll see if I can get a repro case setup when I get some time.

Here's another variant of this error I just happened upon:

![image](https://user-images.githubusercontent.com/945703/40398931-6247775c-5def-11e8-85f0-a437f14f3b90.png)

**Comment by danoscarmike** [comment] 2018-05-24 05:42
@snehashah16 can you please take a look?  Per @stephenplusplus https://github.com/googleapis/nodejs-spanner/issues/183#issuecomment-387828852 :

> Within our PartialResultStream class, we retry after any error from the last resume token. If we don't have a token, we pass the error along to the user and abort the request.

**Comment by snehashah16** [comment] 2018-05-24 21:26
@stephenplusplus 

> Within our PartialResultStream class, we retry after any error from the last resume token. If we don't have a token, we pass the error along to the user and abort the request.

Please use the java client as a reference to handle this scenario:
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java#L2416

**Comment by crwilcox** [comment] 2018-05-31 21:28
@snehashah16 I have looked at the Java code you sent and compared it to the Node.js client. They look very similar
1) try to collect a PartialResultSet object
2) if there is a resume token, it is retryable
3) when it fails, if we have a resume token attempt to retry, otherwise fail.

I noticed that many of our responses come back without resume tokens when I simulate this. I start the request, turn off my network adapter, then proceed to what TCP Read Fail show up. Since I don't have a resume token, I can't know where to retry so it throws.

Node:
```
.intercept('error', function(err) {
      if (lastResumeToken) {
        // We're going to retry from where we left off.
        // Empty queued rows on the checkpoint stream (will not emit them to
        // user).
        batchAndSplitOnTokenStream.reset();
        makeRequest();
        return;
      }

      setImmediate(function() {
        // We won't retry the request, so this will flush any rows the
        // checkpoint stream has queued. After that, we will destroy the user's
        // stream with the same error.
        batchAndSplitOnTokenStream.destroy(err);
      });
    })
```

Java:
```
catch (SpannerException e) {
    if (safeToRetry && e.isRetryable()) {
        span.addAnnotation("Stream broken. Safe to retry",
        ... elided ...
        continue;
    }
    span.addAnnotation("Stream broken. Not safe to retry");
    TraceUtil.endSpanWithFailure(span, e);
    throw e;
```

**Comment by vkedia** [comment] 2018-06-01 13:31
In Java client, we buffer responses till we see a response with resume
token and then we yield all the bufferred rows to the user except if the
buffer is full in which case we will yield irrespective and mark the stream
as unretryable. This makea it very unlikely that we will not have a resume
token when the stream breaks. I believe the buffer size is 10 but pleasw
check in the code.

**Comment by stephenplusplus** [comment] 2018-06-01 14:17
> In Java client, we buffer responses till we see a response with resume
token and then we yield all the bufferred rows to the user except if the
buffer is full in which case we will yield irrespective and mark the stream
as unretryable.

We do all of that, with the exception of marking the stream as unretryable when the buffer is filled. We can add that, but #208 will have to merge first.

> I believe the buffer size is 10 but pleasw check in the code.

Yes, we use 10.

**Comment by crwilcox** [comment] 2018-06-01 20:27
@walshie4 we had a discussion offline with a few of us and are wondering if perhaps your rows are particularly large, or if this is related to a very large node count. If you could provide additional information it could prove helpful. Some things that may be interested:

- Size and shape of the data requested (total rows, columns in the rows, types of rows)
- number of nodes you have for spanner?

This seems specific to your use case and we imagine there is something a bit special here. Any details at all are helpful.

**Comment by walshie4** [comment] 2018-06-01 22:45
I'm currently running with 10 Spanner nodes.  Haven't dug into which query is causing this issue (because the volume and impact of this bug is lesser than the others).

The data in this database is only about ~250mb of data currently, a mix of String, Int64, and ARRAY<String> values.  There is a main table with ~40k rows, with ~8 interleaved tables each containing at most a couple thousand rows in those interleaved tables (most are in the ballpark of 0-20 rows per interleaved table).  One of the interleaved tables has another table interleaved onto those rows, again small datasets, only 10 rows in that table per parent at most (most are 1-4).

This was just off-hand as I'm currently in the middle of something so if there are specific things I didn't cover which could be valuable let me know and I'll get back to y'all shortly when I have a bit more time.

**Comment by crwilcox** [comment] 2018-06-05 01:01
Thanks for the information on this last week @walshie4. We just wrapped up some of the other fixes you had asked for and are going to start looking into this. 

Thanks again for your patience.

**Comment by crwilcox** [comment] 2018-06-06 18:32
I spent the last hour or so reviewing the code path for this. It seems a call to database.run is going to ultimately result in Spanner.requestStream being called

Ideally, GAPIC would manage retrying for these sort of failures. That being said, we may be able to modify this method to handle retrying to harden this.

https://github.com/googleapis/nodejs-spanner/blob/4bfb927029a1ecefd7c2ce096c1886270c0fece8/src/index.js#L824
```
Spanner.prototype.requestStream = function(config) {
  var self = this;

  var stream = streamEvents(through.obj());

  stream.once('reading', function() {
    self.prepareGapicRequest_(config, function(err, requestFn) {
      if (err) {
        stream.destroy(err);
        return;
      }

      requestFn()
        .on('error', function(err) {
          stream.destroy(err);
        })
        .pipe(stream);
    });
  });

  return stream;
};

```

**Comment by JustinBeckwith** [comment] 2018-06-07 23:29
@stephenplusplus *gentle ping*

**Comment by stephenplusplus** [comment] 2018-06-07 23:31
I've been working on putting retry behavior into gax. That would handle retrying on pre-response errors, such as network failures.

**Comment by stephenplusplus** [comment] 2018-06-08 19:36
PR: https://github.com/googleapis/gax-nodejs/pull/241

**Comment by stephenplusplus** [comment] 2018-06-11 17:23
@walshie4 @Duncan00 would you please give my branch a test:

```sh
$ npm install --save stephenplusplus/nodejs-spanner#spp--183
```

This should retry on these types of errors.

**Comment by crwilcox** [comment] 2018-06-15 17:15
Since we haven't heard much in the way of @stephenplusplus fix we are going to proceed to PR and merge it in. Thanks!

**Comment by crwilcox** [comment] 2018-06-19 17:31
@stephenplusplus has merged his fix for gax-nodejs

**Comment by Duncan00** [comment] 2018-06-20 01:51
Thanks. We missed the chance to test it~
Then the next step would be upgrading to use latest `google-gax` and fix the breaking change of instantiate introduced in `0.17.0`
https://github.com/googleapis/gax-nodejs/releases
Please help on it~ Thanks~

**Comment by Duncan00** [comment] 2018-06-20 02:00
If we understand correctly, many different kinds of random errors we are getting in below image will be resolved by this retry logic.
<img width="1545" alt="screen shot 2018-05-25 at 10 30 41 am 3" src="https://user-images.githubusercontent.com/2004375/41633269-956f2566-7470-11e8-94d0-1059261111d4.png">

**Comment by crwilcox** [comment] 2018-06-20 02:18
@Duncan00, we are currently working to release a version of this lib (and many other nodejs google cloud libraries) to work with the latest gax release. We appreciate your patience. In the meantime, you can install an older version of `gax-nodejs`.

**Comment by Duncan00** [comment] 2018-06-20 05:37
Thanks. 
But the fix for retry logic is exactly in `0.17.0`, so we need to wait for this upgrade to resolve this issue.

**Comment by crwilcox** [comment] 2018-06-25 17:58
@stephenplusplus , do we know if this issue is resolved?

**Comment by stephenplusplus** [comment] 2018-06-25 17:59
We need a regen of the GAPIC that has been updated to use 0.17.0 of google-gax, which includes the fix for this.

**Comment by JustinBeckwith** [comment] 2018-06-25 18:05
@crwilcox can you add a synth.py to the repo, run it, up the version of google-gax?

**Closed** 2018-06-25 21:42 UTC
Labels: :rotating_light:, priority: p0, type: bug
