### ISSUE TITLE
Error 13 INTERNAL: GOAWAY received

### ISSUE THREAD

**Issue by Duncan00** [googleapis/nodejs-spanner#492] opened 2018-12-31 02:21 UTC
#### Environment details

  - OS: oldstable debian
  - Node.js version: 8.11.3
  - npm version: 5.6.0
  - `@google-cloud/spanner` version: 2.2.1 (seems no problem in 2.1.0)

#### Steps to reproduce

  1. Do multiple queries in our GET endpoint
  2. The problem occur randomly

Please check out the issue for more information & samples in https://github.com/googleapis/nodejs-spanner/issues/234#issuecomment-434967051.

Thanks!

**Comment by crwilcox** [comment] 2019-01-04 19:17
@Duncan00 do you have an idea of the volume of requests you are sending? I am trying to determine if the message is in error, or if you are really doing enough to be throttled.

**Comment by Duncan00** [comment] 2019-01-11 10:36
Thanks~ We don't get any problems in 2.1.0. But just get problem after upgrading to version: 2.2.1.
But we are not sure whether this version upgrade is totally related.

According to Spanner CPU in google console, we should have much more than enough. Is there any places we need to check whether we have too high volume?

**Comment by crwilcox** [comment] 2019-01-18 22:42
Hi @Duncan00 , would it be possible to set some env vars for us?
```
export GRPC_TRACE=all
export GRPC_VERBOSITY=ERROR
```
This should provide us with a little more information to work with. Right now it is hard to say exactly why you are seeing this error. 

Also, is the repro for this the same as the one provided by a different GitHub user on #234 ?
```
for (let i = 0; i < 10000000; i++) {
  const random = getRandomOffset()
  const result = await database.run({
      sql: 'SELECT * FROM user LIMIT 1 OFFSET @random',
      params: { random },
      json: true,
  })
  await someTable.insert([
      { id: result[0].id, random },
  ])
}
```

**Comment by sduskis** [comment] 2019-01-24 20:24
@crwilcox, can we reduce the priority to p2 on this?

**Comment by JustinBeckwith** [comment] 2019-02-11 02:38
I'm going to go ahead and close this out for now.  If you're still running into issues - let us know!

**Closed by JustinBeckwith** 2019-02-11 02:38 UTC
Labels: priority: p2, type: bug

**Comment by Duncan00** [comment] 2019-02-21 10:29
@crwilcox Thanks~ We are still getting this problem everyday.
Can we set env to the node process?
```
process.env.GRPC_TRACE = 'all';
process.env.GRPC_VERBOSITY= 'ERROR';
```
or we should need to set them in the instance env directly?

We are having 2 different repos getting this problem. They are not in https://github.com/googleapis/nodejs-spanner/issues/234.

**Comment by voltrue2** [comment] 2019-06-14 08:29
We are also seeing this issue. Our client is node-spanner 2.1.0 (Yes. I know it is old).
We see this error occur multiple times when Spanner's response degrades (we do not know the cause of this either...).
If you need more details on this, we are happy to provide more details on this error.
Cheers
