### ISSUE TITLE
database.runTransaction(...) callback sometimes gets called more than once

### ISSUE THREAD

**Issue by voltrue2** [googleapis/nodejs-spanner#46] opened 2017-11-27 02:36 UTC
#### Environment details

  - OS: Mac
  - Node.js version: 7.10.1
  - npm version: 4.2.0
  - @google-cloud/spanner version: 0.8.1

#### Steps to reproduce

  1. Start transaction on a same database, table, and rows with multiple processes (This is to create concurrent read/writes)
  2. Wait and see until some callbacks get called more than once.

NOTE: It seems that this issue occurs when we have concurrent transactions targeting the same table and rows.

Thank you in advance!

**Comment by callmehiphop** [comment] 2017-11-27 12:34
hey @voltrue2, what you are describing is actually happening by design. Sometimes when the same table/rows are being modified by different transactions the server will send an `ABORTED` signal to one of the transactions indicating that it must be rerun in its entirety. The node client will then do that for you by executing the callback again.

If this is something you want to opt out of, I would suggest taking a look at [`Database#getTransaction`](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.56.0/spanner/database?method=getTransaction), which will give you absolute control over the Transaction object and the client library will not rerun anything in the event of an aborted error.

**Comment by voltrue2** [comment] 2017-11-28 02:25
Hi @callmehiphop, thanks for the swift answer. 
I do have another question, though. When I look at my transaction log, a "retry" of a transaction seems to happen after a transaction commit of the same transaction.
Also the transaction commit does not seem to fail.
I am assuming that if the transaction has to be rerun, the commit should also failed?

Thanks!

**Comment by callmehiphop** [comment] 2017-11-28 14:25
Commits aren't the only requests that can fail with an aborted error, it is possible for any request that reads data to fail as well.

**Comment by voltrue2** [comment] 2017-11-29 04:40
So is there a reason for a commit to successfully commit and yet the transaction aborts right after that? 
This seems to be what is happening to me.

Cheers

**Comment by callmehiphop** [comment] 2017-11-29 14:19
No, that sounds like it could be a bug. Would you mind putting together some code that reproduces what you're seeing?

**Comment by voltrue2** [comment] 2017-11-30 03:06
Hello,

Sure thing!

Below is a very simple sample that seems to demonstrate what I have seen.
The number of rows in `items` table and the value of `count` column of `counter` table should match, but they don't.
If you uncomment out the block of code in `_onTask`, it will prevent the multiple calls of the same transactions and it seem to solve the issue (We really lose throughput by doing this though):

```javascript
'use strict';

process.env.GOOGLE_APPLICATION_CREDENTIALS = 'google_credentials.json';

const crypto = require('crypto');
const Spanner = require('@google-cloud/spanner');
const spanner = Spanner({ projectId: 'gcp-kiban-verification' });
const instance = spanner.instance('kiban01');
const db = instance.database('no-takahashi');
const counterId = uuid();

/*
CREATE TABLE counter (
	counterId STRING(32) NOT NULL,
	count INT64 NOT NULL
) PRIMARY KEY (counterId);

CREATE TABLE items (
	id STRING(32) NOT NULL,
	counterId STRING(32) NOT NULL
) PRIMARY KEY (id, counterId);

The value of count of counter table with the matching countId in
should match the number of rows in items table
The issue that I am seeing is that they go out of sync and it seems the cause of it
is the callback of transaction being called multiple times...
* */

for (var i = 0; i < 10; i++) {
	setTimeout(operation, 1);
}

// start transaction -> select -> update -> insert -> end transaction
function operation() {
	var id = uuid();
	var tasks = [
		startTransaction,
		getCountForUpdate,
		updateCount,
		insertItem,
		endTransaction
	];
	var transaction;
	var count;

	runTasks(tasks, done);

	// callback of this gets called more than once...
	function startTransaction(next) {
		console.log('start', id);
		db.runTransaction(function (error, _transaction) {
			if (error) {
				return next(error);
			}
			transaction = _transaction;
			next();
		});
	}

	function getCountForUpdate(next) {
		var query = {
			sql: 'SELECT count FROM counter WHERE counterId = @id',
			params: { id: counterId }
		};
		transaction.run(query, function (error, res) {
			if (error) {
				return next(error);
			}
			if (!res.length) {
				count = 0;
			} else {
				count = parseInt(res[0][0].value.value);
			}
			next();
		});
	}

	function updateCount(next) {
		console.log('update', id);
		var data = [
			{ count: count + 1, counterId: counterId }
		];
		transaction.upsert('counter', data);
		next();
	}

	function insertItem(next) {
		console.log('insert', id);
		var data = [
			{ id: id, counterId: counterId }
		];
		transaction.insert('items', data);
		next();
	}

	function endTransaction(next) {
		console.log('end', id);
		transaction.commit(next);
	}

	function done(error) {
		if (error) {
			console.error('error', error, id);
			return;
		}
		console.log('finished', id);
	}
}

// we could use async library instead here...
// the point is to not use Promise (I have not tested Promise for this behavior)
function runTasks(tasks, cb, _index) {
	if (!_index) {
		_index = 0;
	}
	var task = tasks[_index];
	if (!task) {
		return cb();
	}
	var bind = {
		tasks: tasks,
		cb: cb,
		_index: _index
	};
	task(_onTask.bind(bind));
}

function _onTask(error) {
	// this prevents callback to be executed more than once
	/* we allow callback to be executed more than once to see this behavior
	if (this._called) {
		return console.log('***Error: CallbackAlreadyCalled');
	}
	this._called = true;
	*/
	if (error) {
		return this.cb(error);
	}
	runTasks(this.tasks, this.cb, this._index += 1);
}

// UUID version 4 as a string
function uuid() {
	var rand = crypto.randomBytes(16);
	rand[6] = (rand[6] & 0x0f) | 0x40;
	rand[8] = (rand[8] & 0x3f) | 0x80;
	return rand.toString('hex');
}
```

**Comment by voltrue2** [comment] 2017-12-06 08:32
@callmehiphop 

I know this is a closed issue, but is there any update on this?

I have also contacted Google support on this issue and the support said that it seems to be a bug in the client library.

It would be great, if we can move forward with this. Should I reopen this issue?

Cheers!

**Comment by callmehiphop** [comment] 2017-12-06 17:23
@voltrue2 sorry, I've been a little sidetracked. So after going through your code, I think what you are seeing is the expected behavior. I think @vkedia can elaborate a bit more, but I'm fairly certain trying to simultaneously update the same field through multiple transactions will cause aborted errors for all but 1 transaction.

You could probably work around this by either queuing transactions that you expect conflicts with or switching from `runTransaction` to `getTransaction` and manually retrying `ABORT` errors.

**Comment by vkedia** [comment] 2017-12-06 20:12
If the transaction fails with `ABORTED` then the callback would get invoked again. But I think @voltrue2 is claiming that the callback gets executed again even though the commit succeeded. Why would that happen?
Also why would the count and number of items go out of sync? @voltrue2 is updating them both in the same transaction, so they should never be out of sync unless there is a bug in the client library that is causing those to be committed in separate transactions.

**Comment by callmehiphop** [comment] 2017-12-06 20:53
> But I think @voltrue2 is claiming that the callback gets executed again even though the commit succeeded.

@vkedia Initially that is how I interpreted this issue as well, however after running the code he was kind enough to provide for us, I believe the issue is that he runs the same transaction in parallel. A simpler example of what is happening looks like this:

```js
for (let i = 0; i < 10; i++) {
  setTimeout(runTxn, 1);
}

function runTxn() {
  database.runTransaction(function(err, txn) {
    // a read call
    // an upsert call
    transaction.commit(function(err) {
      // done!
    });
  });
}
```

So when that runs the first transaction is successful, but every subsequent transaction needs to be retried - which I believe is the correct behavior.

**Comment by vkedia** [comment] 2017-12-06 22:27
But that does not explain why are the two tables going out of sync?

**Comment by callmehiphop** [comment] 2017-12-06 23:43
> But that does not explain why are the two tables going out of sync?

@vkedia truthfully I'm not entirely sure why this is happening, but this is what I'm seeing:

1. 10 transactions fire off, each trying to read and then increment a counter.
2. There are no preallocated sessions, so 10 create session requests are sent concurrently
   * The first session is returned from the server within 70ms
   * The second session is returned from the server within 250ms
   * All remaining sessions are returned from the server within 315ms
3. Likely because of the response times, the first 3 transactions commit on the first attempt, putting the counter value to `3`.
4. The other 7 transactions receive an aborted error on commit.
5. All 7 transactions request the counter value and the server returns `2` for each request.
6. All 7 transactions attempt to upsert the counter value to `3`
7. All 7 transactions commit **without** receiving an abort error.

The mismatch comes because we are expecting each transaction to have incremented the counter once, but in fact it was only incremented correctly the first 3 times. This leads me to believe it's not the clients fault, as I would expect the server to

1. return the correct counter value on the retry requests
2. abort n-1 transactions on each retry.

**Comment by vkedia** [comment] 2017-12-07 00:16
Interesting. There are couple of things fishy here.
In step 5 server should be returning `3` for each request and not `2`. In step 7 all transactions should not commit successfully. This leads me to believe that there is some bug around sending transaction ids. Maybe when we retry the transaction, for reads we end up not sending the correct transaction id or we ask it use an implicit transaction or something.
This definitely looks like a bug in the client library and pretty critical one at that. Can you please dig in further and see what is going on? You can try to print each grpc request and then compare what are the transaction ids being sent in each request.

**Comment by callmehiphop** [comment] 2017-12-07 01:53
@vkedia so I've been looking into this and it appears that the client is generating a new transaction id after an aborted error.

The raw request looks like this (I stringified the txn id for readability).

```json
{
  "session": "projects/grape-spaceship-911/instances/gcloud-tests-instance-00941e10/databases/gcloud-tests-database-00944520/sessions/AIwTQWLDqK9n7qbZi_wG2tGQOEJUTihO8TY-t_XGVLryQr5smvcIjlsOkqF_",
  "mutations": [
    {
      "update": {
        "table": "counter",
        "columns": [
          "count",
          "counterId"
        ],
        "values": [
          {
            "values": [
              {
                "stringValue": "2"
              },
              {
                "stringValue": "d93990c8e485422ba262bc89735e7443"
              }
            ]
          }
        ]
      }
    },
    {
      "insert": {
        "table": "items",
        "columns": [
          "counterId",
          "id"
        ],
        "values": [
          {
            "values": [
              {
                "stringValue": "d93990c8e485422ba262bc89735e7443"
              },
              {
                "stringValue": "87ce4248fb734f89aa40851be3b0007a"
              }
            ]
          }
        ]
      }
    }
  ],
  "transactionId": "AIwTQWJ6b4kIjn_5b40UatWQ6lOYb0mGzjx9rA"
}
```

Is there anything that appears out of place to you? I've compared it to the proto file and I believe this is the correct format.

**Comment by vkedia** [comment] 2017-12-07 02:13
This looks ok. Can you also see what was the transactionId used in the query request made in this transaction. That should be the same as here. For each transaction and each retry we need to make sure that same transaction id is used for the query and the commit. And that transaction id should be different from all other transactions.
Generating new transaction id for each retry is the correct behavior.

**Comment by callmehiphop** [comment] 2017-12-07 03:24
@vkedia @voltrue2 so after some more investigating, I just realized there was an error with the reproduction code that prevented it from re-querying the counter (😢). If I refactor the `runTasks` function to the following

```js
  function runTasks(tasks, cb) {
    var task = tasks[0];

    if (!task) {
      return cb(null);
    }

    var config = {
      tasks: tasks.slice(1),
      cb: cb
    };

    task(_onTask.bind(null, config));
  }

  function _onTask(config, error) {
    if (error) {
      return config.cb(error);
    }

    runTasks(config.tasks, config.cb);
  }
```

Everything works as expected and the counter ends up getting set to 10, meaning the tables do not fall out of sync.

**Closed by callmehiphop** 2017-12-07 03:24 UTC

**Comment by vkedia** [comment] 2017-12-07 17:39
Makes sense. Thanks for getting to the bottom of this.

**Comment by voltrue2** [comment] 2017-12-08 01:00
@callmehiphop Thank you for looking into it!
